import { cn } from "@heroui/react"

export const PAGE_CLASS = cn("flex", "min-w-0", "flex-col", "gap-6")
export const STACK_CLASS = cn("flex", "min-w-0", "flex-col", "gap-4")
export const ROW_WRAP_CLASS = cn("flex", "flex-wrap", "items-center", "gap-2")
export const HEAD_ROW_CLASS = cn("flex", "flex-wrap", "items-center", "justify-between", "gap-3")
export const GRID_CLASS = cn("grid", "min-w-0", "grid-cols-1", "items-start", "gap-5", "xl:grid-cols-[minmax(0,1fr)_22rem]")
export const SIDE_CLASS = cn("flex", "min-w-0", "flex-col", "gap-5")
export const LIST_CLASS = cn("flex", "flex-col", "divide-y", "divide-separator")
export const ITEM_CLASS = cn("flex", "min-w-0", "flex-wrap", "items-center", "justify-between", "gap-x-4", "gap-y-2", "py-3", "first:pt-0", "last:pb-0")
export const ITEM_MAIN_CLASS = cn("flex", "min-w-0", "flex-1", "basis-64", "flex-col", "gap-1")
export const TITLE_LINK_CLASS = cn("truncate", "font-semibold", "text-foreground", "underline-offset-2", "hover:underline")
export const FORM_GRID_CLASS = cn("grid", "grid-cols-1", "gap-4", "md:grid-cols-2")
export const TAB_ROW_CLASS = cn("flex", "flex-wrap", "gap-2")
export const FIELD_CLASS = cn("min-h-11", "w-full", "min-w-0", "rounded-lg", "border", "border-separator", "bg-surface-secondary", "px-3", "py-2.5", "text-foreground", "placeholder:text-muted", "focus-visible:outline-2", "focus-visible:outline-focus")
export const LABEL_CLASS = cn("flex", "min-w-0", "flex-col", "gap-1.5", "text-sm", "font-medium")
export const TEXTAREA_CLASS = cn(FIELD_CLASS, "resize-y")
export const FAQ_ROW_CLASS = cn("grid", "grid-cols-1", "gap-3", "rounded-lg", "border", "border-separator", "p-3")
export const SUGGEST_ITEM_CLASS = cn("flex", "min-w-0", "flex-col", "gap-2", "py-3", "first:pt-0", "last:pb-0")
export const PASSAGE_CLASS = cn("flex", "min-w-0", "flex-col", "gap-1.5", "rounded-lg", "border", "border-separator", "bg-surface-secondary", "px-3", "py-2")
export const PASSAGE_TEXT_CLASS = cn("whitespace-pre-wrap", "break-words", "text-sm")
export const NOTE_CLASS = cn("flex", "min-w-0", "flex-col", "gap-2", "py-3", "first:pt-0", "last:pb-0")
export const CARD_LIST_CLASS = cn("flex", "min-w-0", "flex-col", "gap-2", "text-sm")
